url = paste("http://svcs.ebay.com/services/search/FindingService/v1?"
            ,"OPERATION-NAME=findItemsByCategory&"
            ,"SERVICE-VERSION=1.0.0&"
            ,"SECURITY-APPNAME=Sebastia-newheave-PRD-f8e35c535-843c594f&"
            ,"RESPONSE-DATA-FORMAT=XML&"
            ,"REST-PAYLOAD&"
            ,"categoryId=10181&"
            ,"paginationInput.entriesPerPage=2&"
            ,"outputSelector=CategoryHistogram"
            ,sep="") 